// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BlackboardProvenance } from "./BlackboardProvenance";
import type { BlackboardRelationKind } from "./BlackboardRelationKind";

export type BlackboardRelation = { id: string, projectId: string, fromEntryId: string, toEntryId: string, kind: BlackboardRelationKind, note: string | null, confidenceBasisPoints: number, provenance: BlackboardProvenance, revision: number, createdAt: number, updatedAt: number, };
