// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BlackboardEntry } from "./BlackboardEntry";
import type { BlackboardEvidenceFreshness } from "./BlackboardEvidenceFreshness";
import type { BlackboardPremiseFreshness } from "./BlackboardPremiseFreshness";
import type { BlackboardRelation } from "./BlackboardRelation";
import type { BlackboardVerification } from "./BlackboardVerification";

export type BlackboardQueryHit = { entry: BlackboardEntry, relations: Array<BlackboardRelation>, evidenceFreshness: BlackboardEvidenceFreshness, premiseFreshness: BlackboardPremiseFreshness, effectiveVerification: BlackboardVerification, };
