// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BlackboardEntryState } from "./BlackboardEntryState";
import type { BlackboardEvidenceLink } from "./BlackboardEvidenceLink";
import type { BlackboardImportance } from "./BlackboardImportance";
import type { BlackboardKind } from "./BlackboardKind";
import type { BlackboardProvenance } from "./BlackboardProvenance";
import type { BlackboardRootPromotion } from "./BlackboardRootPromotion";
import type { BlackboardStructuredValue } from "./BlackboardStructuredValue";
import type { BlackboardVerification } from "./BlackboardVerification";

export type BlackboardEntry = { id: string, projectId: string, nodeId: string, kind: BlackboardKind, content: string, structuredValue: BlackboardStructuredValue | null, confidenceBasisPoints: number, verification: BlackboardVerification, importance: BlackboardImportance, rootPromotion: BlackboardRootPromotion, evidence: Array<BlackboardEvidenceLink>, provenance: BlackboardProvenance, state: BlackboardEntryState, supersededBy: string | null, revision: number, createdAt: number, updatedAt: number, };
