// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BlackboardEntityKind } from "./BlackboardEntityKind";

export type BlackboardUpdatedNotification = { projectId: string, entityKind: BlackboardEntityKind, entityId: string, revision: number, cursor: string, };
