// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContextMapCoverage } from "./ContextMapCoverage";
import type { ContextMapFreshness } from "./ContextMapFreshness";
import type { ContextMapSource } from "./ContextMapSource";

export type ContextMapQueryHit = { entryId: string, nodeId: string, sourceFingerprint: string, description: string, routingTerms: Array<string>, coverage: ContextMapCoverage, freshness: ContextMapFreshness, source: ContextMapSource, revision: number, createdAt: number, updatedAt: number, lastVerifiedAt: number | null, };
