// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AbsolutePathBuf } from "../AbsolutePathBuf";
import type { ContextMapRegionAnchor } from "./ContextMapRegionAnchor";
import type { ProjectIntelligenceNodeKind } from "./ProjectIntelligenceNodeKind";
import type { ProjectIntelligenceNodeLifecycle } from "./ProjectIntelligenceNodeLifecycle";

export type ProjectIntelligenceNode = { id: string, parentId: string | null, kind: ProjectIntelligenceNodeKind, projectRoot: AbsolutePathBuf | null, relativePath: string, regionAnchor: ContextMapRegionAnchor | null, sourceFingerprint: string | null, lifecycle: ProjectIntelligenceNodeLifecycle, revision: number, updatedAt: number, };
