// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProjectIntelligenceRefreshStatus = { inventoryComplete: boolean, regionCoverageComplete: boolean, filesIndexed: number, regionsIndexed: number, filesSkipped: number, missingFiles: number, truncated: boolean, scanDurationMs: number, publicationDurationMs: number, completedAt: number, };
