// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What became of one unit of a receipt.
 */
export type StatefulMemoryReceiptStatus = "saved" | "alreadyPresent" | "proposed" | "pending" | "omitted" | "notRestored" | "refused" | "undone" | "proposalRestored" | "untouched";
