// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the user adds to project memory.
 */
export type StatefulMemoryAddKind = "rule" | "background" | "decision" | "note";
