// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StatefulAttributionCounters = { worldStateSamples: number, rootEntriesLoaded: number, rootEvidenceRoutesChecked: number, rootEvidenceRoutesCurrent: number, rootEvidenceRoutesStale: number, rootEvidenceRoutesUnavailable: number, rootEvidenceRoutesUnchecked: number, rootUniqueSourcesObserved: number, rootSourceBytesHashed: number, statefulToolCalls: number, failedStatefulToolCalls: number, knowledgeQueryCalls: number, routeQueryCalls: number, evidenceReadCalls: number, steeringQueryCalls: number, conversationReadCalls: number, blackboardWriteCalls: number, contextRefreshCalls: number, obligationWriteCalls: number, runUpdateCalls: number, steeringWriteCalls: number, materialFindingsReused: number,
/**
 * Absent from servers that predate it; read as zero.
 */
packetProjectBytes: number,
/**
 * Absent from servers that predate it; read as zero.
 */
packetContinuityBytes: number,
/**
 * Absent from servers that predate it; read as zero.
 */
memoryRecordsAlreadyPresent: number,
/**
 * Absent from servers that predate it; read as zero.
 */
memoryRecordsRefused: number,
/**
 * Absent from servers that predate it; read as zero.
 */
recipesGrounded: number,
/**
 * Absent from servers that predate it; read as zero.
 */
indexOperations: number,
/**
 * Absent from servers that predate it; read as zero.
 */
indexOperationsPending: number,
/**
 * Absent from servers that predate it; read as zero.
 */
indexWaitMs: number, };
