// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StatefulAttributionCounters } from "./StatefulAttributionCounters";
import type { TokenUsageBreakdown } from "./TokenUsageBreakdown";
import type { TurnTrajectory } from "./TurnTrajectory";

/**
 * Exact totals over a bounded newest-first window of project measurements.
 *
 * Token counts are exposed without estimating monetary cost because the
 * persisted records do not contain authoritative provider pricing, units, or
 * currency.
 */
export type StatefulMeasurementSummary = { projectId: string, measurementCount: number, runCount: number, terminalMeasurementCount: number, completedTurns: number, failedTurns: number, abortedTurns: number, turnsWithTokenUsage: number, durationMs: number, counters: StatefulAttributionCounters, trajectory: TurnTrajectory | null, tokenUsage: TokenUsageBreakdown | null, oldestCreatedAt: number | null, newestCreatedAt: number | null,
/**
 * True when older project measurements exist outside this window.
 */
hasMore: boolean, };
