// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StatefulMemoryReceiptCategory } from "./StatefulMemoryReceiptCategory";
import type { StatefulMemoryReceiptStatus } from "./StatefulMemoryReceiptStatus";

/**
 * One unit of a memory receipt.
 */
export type StatefulMemoryReceiptMember = {
/**
 * Absent when nothing was stored for this unit.
 */
entryId: string | null, revision: number | null, category: StatefulMemoryReceiptCategory, status: StatefulMemoryReceiptStatus,
/**
 * At most 240 bytes. For proposals this is the assistant's labelled reading, not the
 * user's words; applied and stated entries show the user's exact words.
 */
text: string,
/**
 * Whether `text` is shorter than the stored words; the exact words stay readable under
 * `entryId`@`revision` in `statefulMemory/read`.
 */
textShortened: boolean,
/**
 * For a kept proposal that can be applied: the user's exact words an Apply would make
 * theirs, at most 240 bytes, separate from the assistant's reading in `text`. Absent when
 * an Apply would refuse (partial citation, unresolved scope or other dependency).
 */
appliesText: string | null, appliesTextShortened: boolean, };
