// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One investigation rules can be limited to.
 */
export type StatefulMemoryScope = { scopeId: string,
/**
 * The user's words naming it.
 */
title: string, open: boolean,
/**
 * When its rules stop applying, in the user's words.
 */
endCondition: string | null,
/**
 * Whether this thread continues it.
 */
thisThread: boolean, };
