// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StatefulSteeringStatus } from "./StatefulSteeringStatus";

export type StatefulSteering = { id: string, projectId: string, runId: string, input: string, affectedObligationIds: Array<string>, status: StatefulSteeringStatus, resultingStrategyRevision: number | null, reason: string | null, revision: number, createdAt: number, updatedAt: number, };
