// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the user does with the investigations rules can be limited to.
 */
export type StatefulMemoryScopeAction = "list" | "join" | "leave" | "end";
