// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StatefulMemoryReceiptCategory } from "./StatefulMemoryReceiptCategory";
import type { StatefulMemoryReceiptStatus } from "./StatefulMemoryReceiptStatus";

/**
 * One unit of a memory receipt.
 */
export type StatefulMemoryReceiptMember = {
/**
 * Absent when nothing was stored for this unit.
 */
entryId: string | null, revision: number | null, category: StatefulMemoryReceiptCategory, status: StatefulMemoryReceiptStatus,
/**
 * At most 240 bytes. For proposals this is the assistant's labelled reading, not the
 * user's words; applied and stated entries show the user's exact words.
 */
text: string,
/**
 * Whether `text` is shorter than the stored words.
 */
textShortened: boolean, };
