// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StatefulMemoryChangeCategory } from "./StatefulMemoryChangeCategory";
import type { StatefulMemoryOperation } from "./StatefulMemoryOperation";
import type { StatefulMemoryOrigin } from "./StatefulMemoryOrigin";

/**
 * One committed memory change.
 */
export type StatefulMemoryChange = {
/**
 * Position in the project's journal; strictly increasing.
 */
sequence: number, entryId: string | null, revision: number | null, operation: StatefulMemoryOperation, origin: StatefulMemoryOrigin, category: StatefulMemoryChangeCategory, threadId: string | null, turnId: string | null, groupId: string | null,
/**
 * At most 240 bytes, cut on a character boundary.
 */
preview: string,
/**
 * Unix seconds.
 */
createdAt: number, };
