// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StatefulRecapDecision = {
/**
 * At most 240 bytes.
 */
text: string,
/**
 * The recorded reason, when one was recorded; at most 240 bytes.
 */
reason: string | null, };
