// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The kind of knowledge a receipt member holds.
 */
export type StatefulMemoryReceiptCategory = "rule" | "background" | "attributedContext" | "decision" | "brainstormOption" | "ruledOut" | "openCheck" | "note" | "other";
