// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a committed memory change did.
 */
export type StatefulMemoryOperation = "saved" | "promoted" | "corrected" | "forgotten" | "invalidated" | "scopeEnded" | "captureIncomplete";
