// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Retained memory categories. These sections do not assert current applicability.
 */
export type StatefulMemorySection = "userRule" | "pendingRule" | "unverifiedRule" | "decision" | "background" | "knowledge";
