// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * On whose authority a memory entry rests.
 */
export type StatefulMemoryAuthority = "humanDirect" | "assistantReported" | "reportedThirdParty" | "hostObserved" | "legacyUnknown";
