// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StatefulRunBudget } from "./StatefulRunBudget";
import type { StatefulRunStatus } from "./StatefulRunStatus";
import type { StatefulWorkflowMode } from "./StatefulWorkflowMode";

export type StatefulRun = { id: string, projectId: string, threadIds: Array<string>, goal: string, mode: StatefulWorkflowMode, budget: StatefulRunBudget, continuationsUsed: number, status: StatefulRunStatus, strategy: string | null, strategyRevision: number, result: string | null, revision: number, createdAt: number, updatedAt: number, };
