// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the user applies a proposal as. Applied words take project scope.
 */
export type StatefulMemoryApplyCategory = "rule" | "decision" | "ruledOut";
