// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StatefulObligationPacket } from "./StatefulObligationPacket";

export type StatefulObligation = { id: string, projectId: string, runId: string, packet: StatefulObligationPacket, provenanceSourceId: string, sequence: number, revision: number, createdAt: number, };
