// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The last finished piece of work in the project.
 */
export type StatefulRecapWork = { threadId: string,
/**
 * Unix seconds when it finished.
 */
finishedAt: number,
/**
 * The opening of what was asked, at most 240 bytes.
 */
request: string | null, };
