// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Committed changes counted over a stretch of the journal.
 */
export type StatefulMemoryChangeTotals = {
/**
 * New entries saved, commits remembered not included.
 */
saved: number,
/**
 * Commits remembered from the workspace history.
 */
commitsRemembered: number, promoted: number, corrected: number, forgotten: number, invalidated: number, scopesEnded: number,
/**
 * Captures that could not finish.
 */
captureIncomplete: number, };
