// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StatefulAttributionCounters } from "./StatefulAttributionCounters";
import type { StatefulAttributionStatus } from "./StatefulAttributionStatus";

export type StatefulAttributionCompletedNotification = { projectId: string, threadId: string, turnId: string, status: StatefulAttributionStatus, durationMs: number, counters: StatefulAttributionCounters, };
