// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StatefulCaptureOutcome } from "./StatefulCaptureOutcome";
import type { StatefulKnowledgeCategory } from "./StatefulKnowledgeCategory";

/**
 * One saved unit of a counted group receipt.
 */
export type StatefulKnowledgeGroupItem = { entryId: string, revision: number, category: StatefulKnowledgeCategory, outcome: StatefulCaptureOutcome,
/**
 * The entry's content, at most 240 bytes.
 */
text: string, };
