// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An earlier entry that a memory item replaced.
 */
export type StatefulMemoryReplaced = { entryId: string,
/**
 * At most 240 bytes.
 */
content: string,
/**
 * Unix seconds.
 */
replacedAt: bigint, };
