// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The answer a run ended with. The user, not the host, judges it.
 */
export type StatefulHostAnswer = { turnId: string,
/**
 * The final answer exactly as the user received it.
 */
answer: string,
/**
 * States that neither the answer nor the run's work was verified.
 */
basis: string, committedAt: number, };
