// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StatefulAttributionCounters } from "./StatefulAttributionCounters";
import type { StatefulTurnStatus } from "./StatefulTurnStatus";
import type { TokenUsageBreakdown } from "./TokenUsageBreakdown";
import type { TurnTrajectory } from "./TurnTrajectory";

export type StatefulTurnMeasurement = { runId: string, projectId: string, threadId: string, turnId: string, status: StatefulTurnStatus, durationMs: number, counters: StatefulAttributionCounters, trajectory: TurnTrajectory | null,
/**
 * Provider-reported usage accumulated across completed responses in this
 * turn. `None` means no response included usage data.
 */
tokenUsage: TokenUsageBreakdown | null, completedAt: number | null, createdAt: number, updatedAt: number, };
