// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StatefulKnowledgeCategory } from "./StatefulKnowledgeCategory";
import type { StatefulKnowledgeGroupItem } from "./StatefulKnowledgeGroupItem";

/**
 * The committed outcome of one capture (all the rules one message marked), counted: sent
 * once after every unit was stored or refused, so it never claims more than was saved.
 */
export type StatefulKnowledgeGroupCapturedNotification = { projectId: string, threadId: string, turnId: string, groupId: string, category: StatefulKnowledgeCategory,
/**
 * A count the user's words declared ("Two standing rules"), when they did.
 */
declaredCount: number | null, recognized: number,
/**
 * Saved and applied.
 */
saved: number, alreadyPresent: number,
/**
 * Saved but not applied (limited to a task).
 */
pending: number,
/**
 * Recognized but too long to keep whole; not saved.
 */
omitted: number, failed: number,
/**
 * Saved, kept and already-saved units in the order written.
 */
items: Array<StatefulKnowledgeGroupItem>,
/**
 * Openings of omitted units.
 */
omittedItems: Array<string>,
/**
 * The investigation these rules are limited to, in the user's words.
 */
scopeTitle: string | null, };
