// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A run the host ended with an answer that the user, not the host, judges.
 */
export type StatefulHostAnswer = { turnId: string,
/**
 * The final answer exactly as the user received it.
 */
answer: string,
/**
 * What the host observed; states that the answer is not host-verified.
 */
basis: string, committedAt: number, };
