// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StatefulObligationPacket = { examined: Array<string>, rationale: Array<string>, learning: Array<string>, implication: Array<string>, strategy: Array<string>, changed: Array<string>, next: Array<string>, uncertainty: Array<string>, blockers: Array<string>, requestedJudgment: Array<string>, };
