// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What current project memory holds, by what new work does with it.
 */
export type StatefulMemoryCounts = {
/**
 * The user's standing rules, applied.
 */
rules: number,
/**
 * The user's task-limited rules, kept but not applied.
 */
pendingRules: number,
/**
 * Rules not in the user's words, never applied.
 */
unverifiedRules: number, background: number, decisions: number, openChecks: number,
/**
 * Commits remembered from the workspace history.
 */
commits: number, other: number, };
