// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What kind of knowledge a change concerned.
 */
export type StatefulMemoryChangeCategory = "rule" | "background" | "attributedContext" | "decision" | "brainstormOption" | "ruledOut" | "openCheck" | "recipe" | "codeObservation" | "commitObservation" | "note" | "legacy";
