// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StatefulMemoryReceiptKind } from "./StatefulMemoryReceiptKind";
import type { StatefulMemoryReceiptMember } from "./StatefulMemoryReceiptMember";

/**
 * A committed (or refused) memory capture, Apply or Undo. Counts are by member status:
 * saved rules are not proposals, and a refusal never reports a save.
 */
export type StatefulMemoryReceipt = { projectId: string, threadId: string, turnId: string | null,
/**
 * Pass to `statefulMemory/undo`.
 */
receiptId: string, kind: StatefulMemoryReceiptKind,
/**
 * At most 24.
 */
members: Array<StatefulMemoryReceiptMember>,
/**
 * Whether one Undo can reverse what this receipt saved or proposed.
 */
undoable: boolean, };
