// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BlackboardKind } from "./BlackboardKind";
import type { BlackboardProvenanceKind } from "./BlackboardProvenanceKind";
import type { StatefulMemoryAuthority } from "./StatefulMemoryAuthority";
import type { StatefulMemoryReplaced } from "./StatefulMemoryReplaced";
import type { StatefulMemoryScopeState } from "./StatefulMemoryScopeState";
import type { StatefulMemorySection } from "./StatefulMemorySection";

/**
 * One active retained entry; its presence does not assert current applicability.
 */
export type StatefulMemoryItem = { entryId: string, revision: number, section: StatefulMemorySection, kind: BlackboardKind,
/**
 * At most 2,000 bytes; `contentTruncated` says whether more exists.
 */
content: string, contentTruncated: boolean,
/**
 * Who wrote this text.
 */
source: BlackboardProvenanceKind,
/**
 * Unix seconds.
 */
updatedAt: bigint,
/**
 * What this entry replaced, newest first, at most three.
 */
replaces: Array<StatefulMemoryReplaced>,
/**
 * On whose authority the entry rests, when recorded (older entries have none).
 */
authority: StatefulMemoryAuthority | null,
/**
 * The investigation a rule is limited to, in the user's words.
 */
scopeTitle: string | null,
/**
 * Scope state observed for this thread; absent for project-wide entries.
 */
scopeState: StatefulMemoryScopeState | null,
/**
 * Whose words a relayed note keeps, as the user named them.
 */
attributedTo: string | null, };
