// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a knowledge receipt says was saved.
 */
export type StatefulKnowledgeCategory = "rule" | "pendingRule" | "decision" | "recipe" | "finding";
