// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StatefulMemoryReceipt } from "./StatefulMemoryReceipt";

/**
 * Sent when a turn's words were captured, or a capture was refused, or the user applied a
 * proposal or undid a receipt.
 */
export type StatefulMemoryCapturedNotification = { receipt: StatefulMemoryReceipt, };
