// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TurnTrajectory } from "./TurnTrajectory";

/**
 * Reports cumulative trajectory counters for the current turn without
 * exposing raw response items or tool payloads to clients.
 */
export type TurnTrajectoryUpdatedNotification = { threadId: string, turnId: string,
/**
 * Whether this is the terminal snapshot for the turn. Transports may
 * coalesce or drop intermediate updates, but must preserve this update.
 */
isFinal: boolean, trajectory: TurnTrajectory, };
