// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Bounded, content-free counters for one model turn.
 */
export type TurnTrajectory = { completedModelResponses: number, compactions: number, modelToolCalls: number, modelShellToolCalls: number, modelFunctionToolCalls: number, modelCustomToolCalls: number, modelToolSearchCalls: number, modelWebSearchCalls: number, modelImageGenerationCalls: number,
/**
 * Bytes in the JSON serialization of explicit tool output payloads.
 */
toolOutputBytes: number, };
