//! Project-scoped structured knowledge for Stateful Codex.

mod blackboard;
mod blackboard_storage;
mod capture_identity;
mod capture_proposal;
mod capture_source;
mod context_map;
mod context_map_presence;
mod context_map_storage;
mod evidence;
mod hierarchy;
mod indexer;
mod knowledge;
mod repository_observation;
mod repository_observation_storage;
mod search;
mod status;
mod storage;
mod temporal_context;

pub use blackboard::BlackboardEntry;
pub use blackboard::BlackboardEntryId;
pub use blackboard::BlackboardEntryScope;
pub use blackboard::BlackboardEntryState;
pub use blackboard::BlackboardEntryUpdate;
pub use blackboard::BlackboardError;
pub use blackboard::BlackboardEvidenceDependentsQuery;
pub use blackboard::BlackboardEvidenceDependentsResult;
pub use blackboard::BlackboardEvidenceFreshness;
pub use blackboard::BlackboardEvidenceLink;
pub use blackboard::BlackboardHit;
pub use blackboard::BlackboardImportance;
pub use blackboard::BlackboardKind;
pub use blackboard::BlackboardPremiseFreshness;
pub use blackboard::BlackboardPremiseLink;
pub use blackboard::BlackboardProvenance;
pub use blackboard::BlackboardProvenanceKind;
pub use blackboard::BlackboardQuery;
pub use blackboard::BlackboardQueryResult;
pub use blackboard::BlackboardRelation;
pub use blackboard::BlackboardRelationId;
pub use blackboard::BlackboardRelationKind;
pub use blackboard::BlackboardRouteKnowledge;
pub use blackboard::BlackboardRouteKnowledgeQuery;
pub use blackboard::BlackboardStructuredValue;
pub use blackboard::BlackboardVerification;
pub use blackboard::ConfidenceScore;
pub use blackboard::NewBlackboardEntry;
pub use blackboard::NewBlackboardRelation;
pub use blackboard::RootBlackboardProjection;
pub use blackboard::RootBlackboardQuery;
pub use blackboard::RootPromotion;
pub use blackboard_storage::BlackboardStore;
pub use blackboard_storage::BlackboardStoreError;
pub use blackboard_storage::CompletionFence;
pub use blackboard_storage::ContextPolicy;
pub use blackboard_storage::CreateOutcome;
pub use blackboard_storage::MAX_CHANGES_PAGE;
pub use blackboard_storage::MAX_SUPERSEDED_ENTRIES;
pub use blackboard_storage::ReviewContext;
pub use blackboard_storage::ReviewPage;
pub use blackboard_storage::Succession;
pub use blackboard_storage::SupersededEntry;
pub use context_map::ContextMapCoverage;
pub use context_map::ContextMapEntry;
pub use context_map::ContextMapEntryId;
pub use context_map::ContextMapEntryUpdate;
pub use context_map::ContextMapError;
pub use context_map::ContextMapFreshness;
pub use context_map::ContextMapHit;
pub use context_map::ContextMapListQuery;
pub use context_map::ContextMapQuery;
pub use context_map::ContextMapQueryResult;
pub use context_map::ContextMapSource;
pub use context_map::NewContextMapEntry;
pub use context_map_storage::ContextMapStore;
pub use context_map_storage::ContextMapStoreError;
pub use evidence::EvidenceLineRange;
pub use evidence::EvidenceReadError;
pub use evidence::EvidenceReadLocator;
pub use evidence::EvidenceReadRequest;
pub use evidence::EvidenceReadResult;
pub use evidence::EvidenceReader;
pub use evidence::EvidenceRoute;
pub use evidence::MAX_EVIDENCE_READ_BYTES;
pub use hierarchy::HierarchyError;
pub use hierarchy::HierarchyNode;
pub use hierarchy::HierarchyNodeId;
pub use hierarchy::NewHierarchyNode;
pub use hierarchy::NodeKind;
pub use hierarchy::NodeLifecycle;
pub use hierarchy::ProjectRelativePath;
pub use hierarchy::RegionAnchor;
pub use hierarchy::SourceFingerprint;
pub use indexer::ProjectIndexFileRequest;
pub use indexer::ProjectIndexReport;
pub use indexer::ProjectIndexRequest;
pub use indexer::ProjectIndexer;
pub use indexer::ProjectIndexerError;
pub use knowledge::CaptureGroup;
pub use knowledge::CaptureGroupMember;
pub use knowledge::ChangeOperation;
pub use knowledge::ChangeOrigin;
pub use knowledge::ChangeRecord;
pub use knowledge::KnowledgeAuthority;
pub use knowledge::KnowledgeCategory;
pub use knowledge::KnowledgeContext;
pub use knowledge::KnowledgeScope;
pub use knowledge::KnowledgeValidity;
pub use knowledge::MAX_CHANGE_PREVIEW_BYTES;
pub use knowledge::MemberOutcome;
pub use knowledge::MemoryChange;
pub use knowledge::ScopeKind;
pub use knowledge::ScopeState;
pub use knowledge::ThreadScopes;
pub use repository_observation::RepositoryDirtyCoverage;
pub use repository_observation::RepositoryHead;
pub use repository_observation::RepositoryObservation;
pub use repository_observation::RepositoryObservationError;
pub use repository_observation::RepositoryObservationId;
pub use repository_observation::RepositoryRootObservation;
pub use repository_observation::RepositoryRootsCoverage;
pub use repository_observation::RepositoryUnknownReason;
pub use repository_observation::RepositoryWorktree;
pub use repository_observation_storage::RepositoryObservationStore;
pub use repository_observation_storage::RepositoryObservationStoreError;
pub use status::ProjectIntelligenceStatus;
pub use status::ProjectRefreshStatus;
pub use storage::HierarchyRegionSourceUpdate;
pub use storage::HierarchySourceUpdate;
pub use storage::HierarchyStore;
pub use storage::HierarchyStoreError;

pub use blackboard_storage::CaptureEntryWrite;
pub use blackboard_storage::CaptureWrite;
pub use blackboard_storage::CaptureWriteResult;
pub use blackboard_storage::SourceCaptureGroup;
pub use blackboard_storage::SourceCaptureMember;
pub use capture_identity::CAPTURE_NORMALIZER_VERSION;
pub use capture_identity::canonical_capture_words;
pub use capture_identity::retirement_capture_words;
pub use capture_proposal::ProposalAttribution;
pub use capture_proposal::ProposalCategory;
pub use capture_proposal::ProposalContext;
pub use capture_proposal::ProposalDependency;
pub use capture_proposal::ProposalResult;
pub use capture_proposal::ProposalStatus;
pub use capture_proposal::ProposalTemporal;
pub use capture_proposal::ProposalTimeForm;
pub use capture_proposal::SourceProposal;
pub use capture_source::SourceObservation;
pub use capture_source::SourceRangeRead;
pub use capture_source::SourceSeal;
pub use capture_source::SourceSearchCursor;
pub use capture_source::SourceSearchPage;
pub use capture_source::SourceSpan;
pub use capture_source::SourceSpanRole;
pub use temporal_context::EventStatus;
pub use temporal_context::EventTime;
pub use temporal_context::SourceTime;
pub use temporal_context::TemporalAnchor;
pub use temporal_context::TemporalContext;
pub use temporal_context::TemporalDerivation;
pub use temporal_context::TimePrecision;
pub use temporal_context::TimeZone;

pub use capture_source::SourceLink;
pub use capture_source::SourceLinkCursor;
pub use capture_source::SourceLinkPage;
