//! Project-scoped structured knowledge for Stateful Codex.

mod blackboard;
mod blackboard_storage;
mod context_map;
mod context_map_storage;
mod evidence;
mod hierarchy;
mod indexer;
mod search;
mod status;
mod storage;

pub use blackboard::BlackboardEntry;
pub use blackboard::BlackboardEntryId;
pub use blackboard::BlackboardEntryScope;
pub use blackboard::BlackboardEntryState;
pub use blackboard::BlackboardEntryUpdate;
pub use blackboard::BlackboardError;
pub use blackboard::BlackboardEvidenceFreshness;
pub use blackboard::BlackboardEvidenceLink;
pub use blackboard::BlackboardHit;
pub use blackboard::BlackboardImportance;
pub use blackboard::BlackboardKind;
pub use blackboard::BlackboardProvenance;
pub use blackboard::BlackboardProvenanceKind;
pub use blackboard::BlackboardQuery;
pub use blackboard::BlackboardQueryResult;
pub use blackboard::BlackboardRelation;
pub use blackboard::BlackboardRelationId;
pub use blackboard::BlackboardRelationKind;
pub use blackboard::BlackboardRouteKnowledge;
pub use blackboard::BlackboardRouteKnowledgeQuery;
pub use blackboard::BlackboardStructuredValue;
pub use blackboard::BlackboardVerification;
pub use blackboard::ConfidenceScore;
pub use blackboard::NewBlackboardEntry;
pub use blackboard::NewBlackboardRelation;
pub use blackboard::RootBlackboardProjection;
pub use blackboard::RootBlackboardQuery;
pub use blackboard::RootPromotion;
pub use blackboard_storage::BlackboardStore;
pub use blackboard_storage::BlackboardStoreError;
pub use context_map::ContextMapCoverage;
pub use context_map::ContextMapEntry;
pub use context_map::ContextMapEntryId;
pub use context_map::ContextMapEntryUpdate;
pub use context_map::ContextMapError;
pub use context_map::ContextMapFreshness;
pub use context_map::ContextMapHit;
pub use context_map::ContextMapListQuery;
pub use context_map::ContextMapQuery;
pub use context_map::ContextMapSource;
pub use context_map::NewContextMapEntry;
pub use context_map_storage::ContextMapStore;
pub use context_map_storage::ContextMapStoreError;
pub use evidence::EvidenceLineRange;
pub use evidence::EvidenceReadError;
pub use evidence::EvidenceReadLocator;
pub use evidence::EvidenceReadRequest;
pub use evidence::EvidenceReadResult;
pub use evidence::EvidenceReader;
pub use evidence::EvidenceRoute;
pub use evidence::MAX_EVIDENCE_READ_BYTES;
pub use hierarchy::HierarchyError;
pub use hierarchy::HierarchyNode;
pub use hierarchy::HierarchyNodeId;
pub use hierarchy::NewHierarchyNode;
pub use hierarchy::NodeKind;
pub use hierarchy::NodeLifecycle;
pub use hierarchy::ProjectRelativePath;
pub use hierarchy::RegionAnchor;
pub use hierarchy::SourceFingerprint;
pub use indexer::ProjectIndexFileRequest;
pub use indexer::ProjectIndexReport;
pub use indexer::ProjectIndexRequest;
pub use indexer::ProjectIndexer;
pub use indexer::ProjectIndexerError;
pub use status::ProjectIntelligenceStatus;
pub use storage::HierarchyRegionSourceUpdate;
pub use storage::HierarchySourceUpdate;
pub use storage::HierarchyStore;
pub use storage::HierarchyStoreError;
